import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";

import "./globals.scss";
import StoreProvider from "./storeProvider";

const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: 'swap',
  variable: '--font'
});

export const metadata = {
  title: "Next Auth",
  description: "Generated by Next Auth",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <StoreProvider>
          <Toaster position="top-right" />
          {children}
        </StoreProvider>
      </body>
    </html >
  );
}
